In [3]:
# what is 7 to the power of 4
a = 7 ** 4
print(a)

2401


In [2]:
# split this string: s ="Hi there sam!" into a list
s = "hi there sam!"
word_list = s.split()
print(word_list)



['hi', 'there', 'sam!']


In [1]:
# Given the variables: planet = "Earth" diameter = 12742 Use .formate() to print  the following string: The diameter of Earth is 12742km
planet = "Earth"
diameter = 12742

o_string = "The diameter of {} is {}km".format(planet, diameter)
print(o_string)

The diameter of Earth is 12742km


In [5]:
#Gien  this nested list, use indexing to grab the word "hello" 
# list=[1,2,[3,4],[5,[100,200,"hello"]],23,11],1,7]
my_list = [1, 2, [3, 4], [5, [100, 200, ['hello']], 23, 11], 1, 7]
a = my_list[3][1][2]
print(a)

['hello']


In [4]:
#Given this nested dictionary grab the word  "hello". d={"k1":[1,2,3,{'tricy':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d={"k1":[1,2,3,{'tricy':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a=d['k1'][3]['tricy'][3]['target'][3]
print(a)

hello


In [1]:
#Function to grab the emali website domain
def grab(email):
    return email.split('@')[1]

email_address = "user@domain.com"
domain = grab(email_address)
print(domain)

domain.com


In [2]:
#create a basic function that returns true if the world 'dog' is contained in the input string, 
#Don't worry about edge cases like a punctuation being attached to the word dog, but do account
# for capitalization.: findDog('Is there a dog here?)

def find(input):
    return 'dog' in input.lower()

a="Is there a dog here?"
print(find(a))

True


In [ ]:
#q9

In [ ]:
#10

In [13]:
# sample  example for oop concepts
class students:
    course ="BCA"
    def __init__(self):
        print("inside default constructor")
     ##constructor
    def __init__(self,name,s_id,mob):
        self.name=name
        self.s_id=s_id
        self.mob=mob
        print("Inside the  parameterised constructor")
    def display(self): ## method
        print(self.name,"'s id is",self.s_id,"and mobile number is ",self.mob)   

## kiya=students()
kiya=students("kiya",112,9832044937)
kiya.display ##method call
print("These are", students.course,"students") #class call




Inside the  parameterised constructor
These are BCA students


In [3]:
class employees:
    def __init__(self):
       self.empid=input("Enter your id:")
       self.name=input("Enter your name:")
       self.salary=int(input("Enter your salary:"))
       self.number_of_exp=int(input("Enter your experience:"))
       self.hra=0
       self.DA=0
       self.pf=0
       self.bonus=0
       self.net_salary=0
       print("inside init")
    def calhra(self):
        self.hra = 0.35 * self.salary
        print(self.hra)
    def calDA(self):
        self.DA = 0.58 * self.salary
        print("DA",self.DA)
    def calpf(self):
        self.pf = 0.095 * self.salary
        print("pf",self.pf)
    def calbonus(self):
        if self.number_of_exp >= 30:
            self.bonus = 0.59 * self.salary
            print("bonus:",self.bonus)
        elif self.number_of_exp >=23:
            self.bonus = 0.51 * self.salary
            print("bonus:",self.bonus)
        elif self.number_of_exp >=15:
            self.bonus = 0.45 * self.salary
            print("bonus:",self.bonus)
        elif self.number_of_exp >=7:
            self.bonus = 0.33 * self.salary
            print("bonus:",self.bonus)
        else:
            self.bonus = 0.16 * self.salary  
            print("bonus:",self.bonus)

    def calnetsalary(self):
        self.net_salary = self.salary + self.DA + self.hra - self.pf + self.bonus
        print("net_salary",self.net_salary)
keya=employees()
keya.calhra()
keya.calDA()
keya.calpf()
keya.calbonus()
keya.calnetsalary()




    




inside init
1050.0
DA 1739.9999999999998
pf 285.0
bonus: 1770.0
net_salary 7275.0


In [4]:

n = int(input("Enter the number of elements: "))
numbers = []
for i in range(n):
    num = int(input("Enter a number: "))
    numbers.append(num)


new_list = []
for i in range(n // 2):
    new_sum = numbers[i] + numbers[n - i - 1]
    new_list.append(new_sum)


new_list = list(set(new_list))

new_tuple = tuple(new_list)
print("Resulting tuple:", new_tuple)





Resulting tuple: (17, 7)


In [6]:
class numbers:
    def __init__(self, num=0):
        self.num = num
    def setnum(self,num):
        self.num =  num
    def getnum(self):
        return self.num
    def add(self,n2):
        #n3= numbers(self.num + n2.num)
        #return n3
        return self.num  + n2.num
    def power(self,n2):
        return self.num ** n2.num
    def concatenation(self,n2):
        return  str(self.num) + str(n2.num) 
    def mx(self,n2):
        if self.num>n2.num:
            return "n1 is greater"
        else:
            return a,"n2 is greater"

n1 = numbers() #call this in def function 
n1.setnum(2)
print(n1.getnum())
n2=numbers()
n2.setnum(4)
print(n2.getnum())
print(n1.add(n2))
#n3=n1.add(n2)
#n3.getnum()
print(n1.add(n2))
print(n1.power(n2))
print(n1.concatenation(n2))
print(n1.mx(n2))


2
4
6
6
16
24
n2 is greater


In [1]:
#Assignment 3-1
data = [
    (12345, "Diksha", "Diksha r@nuv.ac.in"),
    (45667, "Jiva", "Jiva@nuv.ac.in"),
    (16789, "Ronit", "Ronitd@nuv.ac.in"),
    (69433, "Heena", "Heena@nuv.ac.in")
]

# Accessing elements of the data structure
for item in data:
    print("ID:", item[0])
    print("Name:", item[1])
    print("Email:", item[2])
    print()  # Empty line for separation


ID: 12345
Name: Diksha
Email: Diksha r@nuv.ac.in

ID: 45667
Name: Jiva
Email: Jiva@nuv.ac.in

ID: 16789
Name: Ronit
Email: Ronitd@nuv.ac.in

ID: 69433
Name: Heena
Email: Heena@nuv.ac.in



In [7]:
#1
data = [
    (12345, "Diksha", "Diksha r@nuv.ac.in"),
    (45667, "Jiva", "Jiva@nuv.ac.in"),
    (16789, "Ronit", "Ronitd@nuv.ac.in"),
    (69433, "Heena", "Heena@nuv.ac.in")
]
sid=12345
def ID():
    sid=int(input("Enter any id:"))
    for  d in data :
        #print(d)
        if d[0]== sid:
            print(d)
result=ID()

def name():
    name=input("Enter name:")
    for  d in data :
        #print(d)
        if d[1]== sid:
            print(d)
result=name()



(69433, 'Heena', 'Heena@nuv.ac.in')


In [12]:
#2
Mydict ={
"Enrollment Id" : [12345,45667,16789,69433],
"Student Name": ["Diksha ", "Jiva", "Ronit", "Heena"],
"Email Id": ["Diksha r@nuv.ac.in", "Jiva@nuv.ac.in", "Ronitd@nuv.ac.in",
"Heena@nuv.ac.in"]
}
Mydict["Enrollment Id"][0]
value=int(input("enter id:"))
for i in range(len(Mydict["Enrollment Id"])): # for id input
    if Mydict["Enrollment Id"][i]==value:
        print(Mydict["Enrollment Id"][i])
        print(Mydict["Student Name"][i])
        print(Mydict["Email Id"][i])
        
        enrolid=Mydict["Enrollment Id"][i]
        sname=Mydict["Student Name"][i]
        emailid=Mydict["Email Id"][i]
        print(f"{enrolid:<15}{sname:15}{emailid:25}")      

12345
Diksha 
Diksha r@nuv.ac.in
12345          Diksha         Diksha r@nuv.ac.in       


In [7]:
#3
data=[
    (12345,"diksha","diksha r@nuv.ac.in"),
    (45667,"jiva","jiva @nuv.ac.in"),
    (16789,"ronit","ronitd @nuv.ac.in"),
    (69443,"heena","heena@nuv.ac.in")
]

mydict={"Enroll":[],"Name":[],"Email":[]}

for d in data:
    mydict["Enroll"].append(d[0])
    mydict["Name"].append(d[1])
    mydict["Email"].append(d[2])
mydict

{'enroll': [12345, 45667, 16789, 69443],
 'name': ['diksha', 'jiva', 'ronit', 'heena'],
 'email': ['diksha r@nuv.ac.in',
  'jiva @nuv.ac.in',
  'ronitd @nuv.ac.in',
  'heena@nuv.ac.in']}

In [15]:
#3
data=[
    (12345,"diksha","diksha r@nuv.ac.in"),
    (45667,"jiva","jiva @nuv.ac.in"),
    (16789,"ronit","ronitd @nuv.ac.in"),
    (69443,"heena","heena@nuv.ac.in")
]

mydict={"Enroll":[],"Name":[],"Email":[]}

mydict["Enrollment id"]=[d[0]for d in data]
mydict["Name"]=[d[1]for d in data]
mydict["Email"]=[d[2]for d in data]
mydict

{'Enroll': [],
 'Name': ['diksha', 'jiva', 'ronit', 'heena'],
 'Email': ['diksha r@nuv.ac.in',
  'jiva @nuv.ac.in',
  'ronitd @nuv.ac.in',
  'heena@nuv.ac.in'],
 'Enrollment id': [12345, 45667, 16789, 69443]}

In [22]:
#4
import json
# fu=open("bcadetail.json",'w')
# jsondata=json.dumps(mydict)
# fu.write(jsondata)
fr=open("bcadetail.json","r")
allbcadetail=json.load(fr)
allbcadetail


{'Enroll': [],
 'Name': ['diksha', 'jiva', 'ronit', 'heena'],
 'Email': ['diksha r@nuv.ac.in',
  'jiva @nuv.ac.in',
  'ronitd @nuv.ac.in',
  'heena@nuv.ac.in'],
 'Enrollment id': [12345, 45667, 16789, 69443]}

In [ ]:
#5.
Mydict={
    12001:{"name":"Gujarat","population":10,"no_of_uni":20},
    12002:{"name":"Maharashtra","population":19,"no_of_uni":36},
    12003:{"name":"Rajasthan","population":13,"no_of_uni":31},
    12004:{"name":"Madhya Pradesh","population":14,"no_of_uni":21},
    12005:{"name":"Punjab","population":12,"no_of_uni":13},
    12006:{"name":"Karnataka","population":23,"no_of_uni":31},
    12007:{"name":"Tamilnadu","population":25,"no_of_uni":29},
    12008:{"name":"Kerala","population":21,"no_of_uni":15},
}

In [4]:
import csv
with open('Q5data.csv') as csvdata:
    for n in csvdata:
        print(n)

stateid,name,population in crores,No.of.university

12001,Gujarat,10,29,

12002,Maharashtra,19,36,

12003,Rajasthan,13,31,

12004,Madhya Pradesh,14,21,

12005,Punjab,12,13,

12006,Karnataka,23,31,

12007,Tamilnadu,25,29,

1208,Kerala,21,15


In [1]:
!py -m pip install numpy

'py' is not recognized as an internal or external command,
operable program or batch file.


In [1]:
#UNIT 2
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(1)

array([0.0220103])

In [13]:
np.random.rand(25)

array([0.89331064, 0.11302179, 0.58578147, 0.60570341, 0.73913407,
       0.6592345 , 0.30267391, 0.49170753, 0.77832324, 0.48068264,
       0.67787159, 0.84864894, 0.43309581, 0.4414779 , 0.75401026,
       0.92436636, 0.36214559, 0.54178476, 0.34400178, 0.61514447,
       0.61189178, 0.85316149, 0.15867998, 0.77316476, 0.67197223])

In [5]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [8]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
mat=np.arange(1,26).reshape(5,5)

In [38]:
mat[2:5 , 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
mat[3:4,4:5]

array([[20]])

In [46]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [48]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [52]:
np.std(mat)

7.211102550927978

In [55]:
#columns
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [56]:
#rows
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [11]:
oneD=np.arange(0,12)
#oneD.ndim
oneD.dtype

dtype('int32')

In [12]:
twoD=np.arange(0,12).reshape(3,4)
twoD
#twoD.ndim
twoD.shape

(3, 4)

In [13]:
threeD=np.arange(0,12).reshape(3,2,2)
threeD.ndim

3

In [87]:
np.ones(15).reshape(5,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.empty(3)

array([1.11918508e-311, 0.00000000e+000, 2.35541598e-312])

In [83]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
maths=np.random.randint(0,100,20)
maths

array([54, 50, 24, 94, 69, 17, 88, 80, 52, 82, 30, 30, 11,  4, 70, 69,  7,
       82, 30, 80])

In [103]:
np.sort(maths)

array([ 4,  7, 11, 17, 24, 30, 30, 30, 50, 52, 54, 69, 69, 70, 80, 80, 82,
       82, 88, 94])

In [112]:
np.flip(maths)

array([80, 30, 82,  7, 69, 70,  4, 11, 30, 30, 82, 52, 80, 88, 17, 69, 94,
       24, 50, 54])

In [15]:
np.eye(5).reshape(25,)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [20]:
one=np.arange(1,10).reshape(3,3)
two=np.arange(10,13)
three=np.append(one,two).reshape(4,3)
three

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
#19
#[1,0,2,0,0,4,0,8]
import numpy as np

np.nonzero([1,0,2,0,0,4,0,8])

(array([0, 2, 5, 7], dtype=int64),)

In [3]:
#18
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
#20
mat=np.ones((10,10))
mat[1:9,1:9]=0
mat

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
#21
mat=np.ones((8,8))
mat[0::2,0::2]=0
mat[1::2,1::2]=0
mat

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [23]:
mat=np.ones((4,4))
mat[0::2,0::2]=0
mat[1::2,1::2]=0
mat

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [45]:
#checkboard example
mat=np.arange(0,25).reshape(5,5)
mat[0::2,0::2]=0
mat[1::2,1::2]=0
mat


array([[ 0,  1,  0,  3,  0],
       [ 5,  0,  7,  0,  9],
       [ 0, 11,  0, 13,  0],
       [15,  0, 17,  0, 19],
       [ 0, 21,  0, 23,  0]])

In [47]:
#22
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))
print("matrix1:",a)
print("matrix2:",b)

add=a+b
print("add",a)

multiply=a@b
print("multiply:",multiply)

sub=a-b
print("sub",sub)

matrix1: [[6 5 5]
 [3 8 1]
 [5 6 5]]
matrix2: [[1 9 7]
 [5 6 6]
 [6 0 4]]
add [[6 5 5]
 [3 8 1]
 [5 6 5]]
multiply: [[61 84 92]
 [49 75 73]
 [65 81 91]]
sub [[ 5 -4 -2]
 [-2  2 -5]
 [-1  6  1]]


In [18]:
import numpy as np
mat=np.ones((8,8))*7
mat[2:6,2:6]=0
mat

array([[7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 0., 0., 0., 0., 7., 7.],
       [7., 7., 0., 0., 0., 0., 7., 7.],
       [7., 7., 0., 0., 0., 0., 7., 7.],
       [7., 7., 0., 0., 0., 0., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7.]])

In [13]:
threeD=np.arange(0,18).reshape(2,3,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [14]:
threeD.ndim

3

In [19]:
np.std(threeD)

5.188127472091127

In [2]:
#Series
import pandas as pd
import numpy as np
marks=pd.Series([95,65,75],index=["python","dsa","dbms"])
marks


python    95
dsa       65
dbms      75
dtype: int64

In [10]:
marks.keys()

Index(['python', 'dsa', 'dbms'], dtype='object')

In [11]:
marks.values

array([95, 65, 75], dtype=int64)

In [12]:
d={"name":'sikha',"email":'sikha11@gmail.com',"address":'manjalpur'}

In [13]:
pd.Series(d)

name                   sikha
email      sikha11@gmail.com
address            manjalpur
dtype: object

In [14]:
student=pd.Series(d)

In [15]:
student.keys

<bound method Series.keys of name                   sikha
email      sikha11@gmail.com
address            manjalpur
dtype: object>

In [16]:
student.values

array(['sikha', 'sikha11@gmail.com', 'manjalpur'], dtype=object)

In [3]:
#dataframe
from numpy.random import randn
np.random.seed(1)
df=pd.DataFrame(np.random.randint(1,100,(4,4)),index=['Riya','Siya','Kiya','Jiya'],columns=['Python','Data Science','Rdbms','Computing'])
df

Python  Data Science  Rdbms  Computing
Riya      38            13     73         10
Siya      76             6     80         65
Kiya      17             2     77         72
Jiya       7            26     51         21

In [27]:
df[['Python','Data Science']]

Python  Data Science
Riya      38            13
Siya      76             6
Kiya      17             2
Jiya       7            26

In [28]:
df.iloc[2]

Python          17
Data Science     2
Rdbms           77
Computing       72
Name: Kiya, dtype: int32

In [30]:
df[['Data Science','Rdbms']]

Data Science  Rdbms
Riya            13     73
Siya             6     80
Kiya             2     77
Jiya            26     51

In [31]:
df.loc[['Siya','Riya']]

Python  Data Science  Rdbms  Computing
Siya      76             6     80         65
Riya      38            13     73         10

In [36]:
df['Names']=['Tina','Kiya','Sina','Rina']
df

Python  Data Science  Rdbms  Computing Names
Riya      38            13     73         10  Tina
Siya      76             6     80         65  Kiya
Kiya      17             2     77         72  Sina
Jiya       7            26     51         21  Rina

In [37]:
df.set_index('Names')

Python  Data Science  Rdbms  Computing
Names                                        
Tina       38            13     73         10
Kiya       76             6     80         65
Sina       17             2     77         72
Rina        7            26     51         21

In [9]:
df['Total']=df['Python']+df['Data Science']+df['Rdbms']+df['Computing']
df

Python  Data Science  Rdbms  Computing  Total
Riya      38            13     73         10    134
Siya      76             6     80         65    227
Kiya      17             2     77         72    168
Jiya       7            26     51         21    105

In [10]:
df.drop('Names',axis=1)


KeyError: "['Names'] not found in axis"

In [11]:
df

Python  Data Science  Rdbms  Computing
Riya      38            13     73         10
Siya      76             6     80         65
Kiya      17             2     77         72
Jiya       7            26     51         21

In [4]:
df1=pd.read_csv('Q5data.csv')
df1

stateid  name  population in crores  No.of.university
12001         Gujarat    10                    29               NaN
12002     Maharashtra    19                    36               NaN
12003       Rajasthan    13                    31               NaN
12004  Madhya Pradesh    14                    21               NaN
12005          Punjab    12                    13               NaN
12006       Karnataka    23                    31               NaN
12007       Tamilnadu    25                    29               NaN
1208           Kerala    21                    15               NaN

In [5]:
#Q1
np.random.seed(1)
df=pd.DataFrame(np.random.randint(1,100,(5,3)),index=['Element 1','Element 2','Element 3','Element 4','Element 5'],columns=['Product Id','Product Name','Product Price'])
df

Product Id  Product Name  Product Price
Element 1          38            13             73
Element 2          10            76              6
Element 3          80            65             17
Element 4           2            77             72
Element 5           7            26             51

In [17]:
#Q3
df.loc[['ProductId']]

Element 1  Element 2  Element 3  Element 4  Element 5
ProductId         38         13         73         10         76

In [22]:
#Q3
df.iloc[2]

Product Id       80
Product Name     65
Product Price    17
Name: Element 3, dtype: int32

In [26]:
#Q4
df.loc['Element 3':]

Product Id  Product Name  Product Price
Element 3          80            65             17
Element 4           2            77             72
Element 5           7            26             51

In [35]:
#Q5
df.iloc[2,2],['Product Price']

(17, ['Product Price'])

In [5]:
df.iloc[2,2]
df.loc['Element 2':,['Product Price']]

Product Price
Element 2              6
Element 3             17
Element 4             72
Element 5             51

In [6]:
#Q8
df=pd.DataFrame(np.random.randint(1,100,(4,3)),index=['Riya','Siya','Kiya','Jiya'],columns=['Python','Data Science','Rdbms'])
df


Python  Data Science  Rdbms
Riya      21            19     85
Siya      12            29     30
Kiya      15            51     69
Jiya      88            88     95

In [14]:
df['Python']>40

Riya     True
Siya     True
Kiya    False
Jiya    False
Name: Python, dtype: bool

In [15]:
df.loc[df['Python']>40,'Python']

Riya    48
Siya    72
Name: Python, dtype: int32

In [16]:
#Q9
df+2

Python  Data Science  Rdbms
Riya      50            75     33
Siya      74             6     73
Kiya      24            52     60
Jiya       6            71     27

In [17]:
df

Python  Data Science  Rdbms
Riya      48            73     31
Siya      72             4     71
Kiya      22            50     58
Jiya       4            69     25

In [25]:
df2=(df+2)
df2

Python  Data Science  Rdbms
Riya      50            75     33
Siya      74             6     73
Kiya      24            52     60
Jiya       6            71     27

In [26]:
df3=(df+50)
df3

Python  Data Science  Rdbms
Riya      98           123     81
Siya     122            54    121
Kiya      72           100    108
Jiya      54           119     75

In [27]:
df2[df2>100]=100
df2

Python  Data Science  Rdbms
Riya      50            75     33
Siya      74             6     73
Kiya      24            52     60
Jiya       6            71     27

In [ ]:
#AND-&   #OR-|

In [30]:
#Q10
df3[(df3['Python']>80) & (df3['Data Science']>100)]


Python  Data Science  Rdbms
Riya      98           123     81

In [31]:
#Q11
df[df.index.str.startswith('S')]

Python  Data Science  Rdbms
Siya      72             4     71

In [33]:
#Q12
df[df.index.str.endswith('A')]
df

Python  Data Science  Rdbms
Riya      48            73     31
Siya      72             4     71
Kiya      22            50     58
Jiya       4            69     25

In [9]:
#Q13
df['totals']=df['Python']+df['Data Science']+df['Rdbms']
df

Python  Data Science  Rdbms  totals
Riya      21            19     85     125
Siya      12            29     30      71
Kiya      15            51     69     135
Jiya      88            88     95     271

In [30]:
df['Percentage']=((df['Python']+df['Data Science']+df['Rdbms']))/400*100
df

Python  Data Science  Rdbms  totals  Percentage Result
Riya      21            19     85     125       31.25   Pass
Siya      12            29     30      71       17.75   Fail
Kiya      15            51     69     135       33.75   Pass
Jiya      88            88     95     271       67.75   Pass

In [50]:
df.drop('Total',axis=1,inplace=True)

In [22]:
df

Python  Data Science  Rdbms  totals  Percentage Result
Riya      21            19     85     125       31.25   Pass
Siya      12            29     30      71       17.75   Fail
Kiya      15            51     69     135       33.75   Pass
Jiya      88            88     95     271       67.75   Pass

In [25]:
#Q14
df["Result"]=df['Percentage']>30
df

Python  Data Science  Rdbms  totals  Percentage Result
Riya      21            19     85     125       31.25   Pass
Siya      12            29     30      71       17.75   Fail
Kiya      15            51     69     135       33.75   Pass
Jiya      88            88     95     271       67.75   Pass

In [18]:
df.loc[df['Percentage']>30,'Result']="Pass"
df

Python  Data Science  Rdbms  totals  Percentage Result
Riya      21            19     85     125       31.25   Pass
Siya      12            29     30      71       17.75   Fail
Kiya      15            51     69     135       33.75   Pass
Jiya      88            88     95     271       67.75   Pass

In [28]:
df.loc[df['Percentage']<30,'Result']="Fail"
df

Python  Data Science  Rdbms  totals  Percentage Result
Riya      21            19     85     125       31.25   Pass
Siya      12            29     30      71       17.75   Fail
Kiya      15            51     69     135       33.75   Pass
Jiya      88            88     95     271       67.75   Pass

In [34]:
df['Result']=np.where(df['Percentage']<60,"Fail","Pass")
df

Python  Data Science  Rdbms  totals  Percentage Result
Riya      21            19     85     125       31.25   Fail
Siya      12            29     30      71       17.75   Fail
Kiya      15            51     69     135       33.75   Fail
Jiya      88            88     95     271       67.75   Pass

In [99]:
#Q15
df.loc[df['Percentage']>30,'Grade']='C'
df.loc[df['Percentage']>60,'Grade']='B'

df


Python  Data Science  Rdbms  totals  Percentage Result Grade
Riya      21            19     85     125       31.25   Fail     C
Siya      12            29     30      71       17.75   Fail     F
Kiya      15            51     69     135       33.75   Fail     C
Jiya      88            88     95     271       67.75   Pass     B

In [100]:
df.loc[df['Percentage']>10,'Grade']='F'
df.loc[df['Percentage']>60,'Grade']='B'
df.loc[df['Percentage']>30,'Grade']='C'
df

Python  Data Science  Rdbms  totals  Percentage Result Grade
Riya      21            19     85     125       31.25   Fail     C
Siya      12            29     30      71       17.75   Fail     F
Kiya      15            51     69     135       33.75   Fail     C
Jiya      88            88     95     271       67.75   Pass     C